version: '2'
services:
  webapp:
    image: ericskang/webapp:latest
    depends_on:
      - mssql
    container_name: webapp
    ports:
      - "80:3000"
  slacker:
    image: ericskang/slacker-node-runner:latest
    depends_on: 
      - mssql
    container_name: slacker
    ports:
      - "8000:8000"
  mssql:
    image: ericskang/unittestdb:latest
    container_name: mssql
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "Yukon900"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
