---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlnfs1 
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Recycle 
  nfs:
    path: "/k8svolumes/sqlpv1"
    server: "10.135.10.138"

