---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mssql-fci
  namespace: production
  labels:
    db: mssql-fci
spec:
  serviceName: mssql-fci
  replicas: 1
  template:
    metadata: 
      labels: 
        db: mssql-fci
    spec: 
      volumes:
        - name: sqlvol 
          persistentVolumeClaim:
            claimName: sqlpvclaim
      containers:
        - image: microsoft/mssql-server-linux:latest
          name: mssql-fci
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "SqlDevOps2017"
            - name: MSSQL_PID
              value: "Developer"
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: sqlvol
---
kind: Service
apiVersion: v1
metadata:
  name: mssql-fci
  namespace: production
spec:
  selector:
    db: mssql-fci
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 31432
  type: NodePort
  