---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: sql-full-backup-job
  namespace: db-hosts
spec:
  schedule: "*/59 */23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sql-full-backup-job
            image: ericskang/cronjobs:backup
            args:
            - /bin/bash
            - -c
            - ./full-backup.sh
          restartPolicy: OnFailure